#!/usr/bin/env bash
make &&
sudo cp wpa_supplicant wpa_cli /usr/local/sbin/
sudo cp wpa_supplicant_soap.service /lib/systemd/system/
if [ "$?" -ne "0" ]; then
  exit 1;
fi
if [ -n "$CLEARSYSLOG" ]; then
echo "" | sudo tee /var/log/syslog
  if [ "$?" -ne 0 ]; then
  exit 1;
  fi
fi

